datasets:
    # - turbulent_radiative_layer_2D
    - cylinder_sym_flow_water
    - cylinder_pipe_flow_water
    - object_periodic_flow_water
    - object_sym_flow_water
    - object_sym_flow_air
    - heated_object_pipe_flow_air
    - cooled_object_pipe_flow_air
    - rayleigh_benard_obstacle
    - twophase_flow
    - rayleigh_benard
    - shear_flow
    - euler_multi_quadrants_periodicBC

num_channels: 5
min_stride: 1
max_stride: 8

T_in: 4
T_out: 1

batch_size: 64
num_workers: 16

model: DPOT # only 25 GB VRAM at 128 batch size

##########################################################
########## Medium model
##########################################################
out_layer_dim: 32
res: 128
patch_size: 8
noise_scale: 0.0005
modes: 32
width: 1024
mlp_ratio: 4
n_blocks: 8
n_layers: 12
act: gelu
normalize: true

compile: false
amp: true