datasets:
    # - turbulent_radiative_layer_2D
    - cylinder_sym_flow_water
    - cylinder_pipe_flow_water
    - object_periodic_flow_water
    - object_sym_flow_water
    - object_sym_flow_air
    - heated_object_pipe_flow_air
    - cooled_object_pipe_flow_air
    - rayleigh_benard_obstacle
    - twophase_flow
    - rayleigh_benard
    - shear_flow
    - euler_multi_quadrants_periodicBC

resume_path: null

num_channels: 5
min_stride: 1
max_stride: 8

use_writer: True

T_in: 4
T_ar: 1
T_bundle: 1
use_ln: 0
normalize: True
grad_clip: 10.0



batch_size: 16
num_workers: 8

beta1: 0.9
beta2: 0.9
lr: 0.0001
epochs: 4
epoch_length: 1000
eval_length: 200

lr_method: cycle
warmup_epochs: 1

model: DPOT
opt: adam
comment: 'M'
##########################################################
########## Medium model
##########################################################
out_layer_dim: 32
res: 128
patch_size: 8
noise_scale: 0.0005
modes: 32
width: 1024
mlp_ratio: 4
n_blocks: 8
n_layers: 12
act: gelu


###################
### Small
##################

# res: 128
# patch_size: 8
# noise_scale: 0.0005
# modes: 32
# width: 1024
# mlp_ratio: 1
# n_blocks: 8
# n_layers: 6
# out_layer_dim: 32
# act: gelu


###################
### Tiny
##################

# res: 128
# patch_size: 8
# noise_scale: 0.0005
# modes: 32
# width: 512
# mlp_ratio: 1
# n_blocks: 4
# n_layers: 4
# out_layer_dim: 32
# act: gelu
