datasets:
  - ccc
  - ddd
data_path: ./data/well/mixed_medium
log_path: ./results/well/mixed_medium/pretrain_medium

num_channels: 1
min_stride: 1
max_stride: 5
normalize: 0

use_writer: True
step_size: 100
step_gamma: 0.5

T_in: 10
T_ar: 1
T_bundle: 1
use_ln: 0
normalize: 0
grad_clip: 10000.0




num_gpus: 8
batch_size: 20
num_workers: 8

beta1: 0.9
beta2: 0.9
lr: 0.001
epochs: 1000
lr_method: cycle
warmup_epochs: 200
epochs: 1000

##########################################################
########## Medium model
##########################################################
model: DPOT
opt: adam
comment: 'M'
out_layer_dim: 32
res: 128
patch_size: 8
noise_scale: 0.0005
modes: 32
width: 1024
mlp_ratio: 4
n_blocks: 8
n_layers: 12